---
- name: This is for eight steps exersise
  vars:  
    ansible_user: user1
    ansible_password: user1
  hosts: web
  tasks:
  - name: Create a Group
    group: name=deploy
  - name: Create a User and assign to Group
    user: name=deploy-user group=deploy shell=/bin/bash state=present
  - name: Install the httpd apps
    yum: name=httpd
  - name: start the httpd service
    service: name=httpd state=started
  - name: Copy HTML Content to a file
    copy: dest=/var/www/html/index.html content='<html><h1>Welcome to HPE</h1></html>'
  - name: Install GIT
    yum: name=git state=present
  - name: Install WGET
    yum: name=wget state=present
  - name: Clone Code From GIT
    git: dest=/home/harish/GitRepo1 repo=https://github.com/scmgalaxy/ansible-role-template  
...
